apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
spec:
  selector:
    app: shopping-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31212
      name: http
  type: LoadBalancer
